version: '3.5'

services:
  postgres-gophermart:
    container_name: postgres-keeper
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keeper
      PGDATA: /data/postgres
    volumes:
       - postgres-keeper:/data/postgres
    ports:
      - "35432:5432"

  minio:
    container_name: minio
    image: bitnami/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_USE_SSL: "0"
      MINIO_DEFAULT_BUCKETS: "bucket"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 3


volumes:
    postgres-keeper:
    minio_data: