version: '3.5'

services:
  postgres-gophermart:
    container_name: postgres-keeper
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keeper
      PGDATA: /data/postgres
    volumes:
       - postgres-keeper:/data/postgres
    ports:
      - "35432:5432"
volumes:
    postgres-keeper:
